[package]
name = "pluvia-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pluvia-core = { path = "../pluvia-core" }
tokio = { version = "1.40", features = ["full"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
thiserror = "2.0"
